export const CATEGORY_MAP = {
  // ===== WEB & APP DEVELOPMENT =====
  "web_development": [
    "html_css",
    "javascript",
    "typescript",
    "react",
    "vue",
    "angular",
    "svelte",
    "next_js",
    "nuxt_js",
    "gatsby",
    "remix",
    "astro",
    "tailwind_css",
    "bootstrap",
    "material_ui",
    "responsive_design",
    "progressive_web_apps",
    "web_performance",
    "accessibility"
  ],
  
  "web_stacks": [
    "mern_stack",
    "mean_stack",
    "pern_stack",
    "t3_stack",
    "lamp_stack",
    "jamstack",
    "serverless_architecture",
    "static_site_generation",
    "ssr_ssg",
    "headless_cms"
  ],

  "backend_development": [
    "nodejs",
    "expressjs",
    "fastapi",
    "flask",
    "django",
    "spring_boot",
    "java",
    "python",
    "c_sharp",
    "php",
    "laravel",
    "symfony",
    "golang",
    "rust",
    "ruby_on_rails",
    "asp_net_core",
    "graphql",
    "rest_api",
    "grpc",
    "websockets",
    "real_time_applications"
  ],

  "mobile_development": [
    "react_native",
    "flutter",
    "ios_development",
    "android_development",
    "swift",
    "kotlin",
    "xamarin",
    "cordova",
    "nativescript",
    "ionic",
    "mobile_ui_design",
    "mobile_performance",
    "push_notifications",
    "app_distribution"
  ],

  "database_technologies": [
    "sql",
    "mysql",
    "postgresql",
    "mongodb",
    "firebase",
    "redis",
    "elasticsearch",
    "cassandra",
    "dynamodb",
    "oracle",
    "sqlite",
    "graphql_databases",
    "database_design",
    "query_optimization",
    "indexing_strategies"
  ],

  "frontend_development": [
    "react_advanced",
    "state_management",
    "redux",
    "zustand",
    "context_api",
    "axios_fetch",
    "form_handling",
    "animations",
    "canvas_webgl",
    "svg_graphics",
    "charting_libraries",
    "data_visualization",
    "testing_frontend",
    "debugging_tools"
  ],

  "fullstack_development": [
    "fullstack_architecture",
    "endtoend_development",
    "authentication",
    "authorization",
    "session_management",
    "deployment",
    "scaling_applications",
    "monolith_vs_microservices",
    "design_patterns",
    "system_design"
  ],

  // ===== PROGRAMMING LANGUAGES & FUNDAMENTALS =====
  "programming_languages": [
    "javascript_fundamentals",
    "python_fundamentals",
    "java_fundamentals",
    "c_programming",
    "cpp_programming",
    "csharp_fundamentals",
    "go_programming",
    "rust_fundamentals",
    "php_fundamentals",
    "ruby_fundamentals",
    "perl_basics",
    "kotlin_basics",
    "swift_basics",
    "scala_basics",
    "r_programming"
  ],

  "dsa_algorithms": [
    "data_structures",
    "arrays_linked_lists",
    "stacks_queues",
    "trees_graphs",
    "sorting_algorithms",
    "searching_algorithms",
    "dynamic_programming",
    "greedy_algorithms",
    "backtracking",
    "bit_manipulation",
    "string_algorithms",
    "number_theory",
    "geometry_algorithms",
    "graph_algorithms",
    "competitive_programming"
  ],

  // ===== CLOUD & DEVOPS =====
  "cloud_devops": [
    "aws_fundamentals",
    "aws_ec2",
    "aws_s3",
    "aws_lambda",
    "aws_rds",
    "aws_dynamodb",
    "aws_vpc",
    "aws_iam",
    "aws_cloudformation",
    "aws_cli",
    "azure_fundamentals",
    "azure_vms",
    "azure_app_service",
    "azure_sql",
    "azure_storage",
    "google_cloud_fundamentals",
    "gcp_compute_engine",
    "gcp_cloud_functions",
    "gcp_firestore",
    "gcp_bigquery"
  ],

  "containerization": [
    "docker_fundamentals",
    "docker_compose",
    "kubernetes_basics",
    "kubernetes_advanced",
    "helm_charts",
    "container_orchestration",
    "container_registry",
    "dockerfile_optimization",
    "container_security"
  ],

  "cicd_automation": [
    "git_version_control",
    "github_actions",
    "gitlab_ci",
    "jenkins",
    "circleci",
    "travis_ci",
    "buildpipelines",
    "automated_testing",
    "continuous_deployment",
    "infrastructure_as_code"
  ],

  "infrastructure": [
    "terraform",
    "ansible",
    "puppet",
    "chef",
    "cloudformation",
    "bicep",
    "iac_best_practices",
    "infrastructure_monitoring",
    "logging_aggregation",
    "tracing_observability"
  ],

  "devops_operations": [
    "linux_administration",
    "windows_server",
    "networking_fundamentals",
    "dns_configuration",
    "load_balancing",
    "reverse_proxy",
    "ssl_tls_certificates",
    "firewall_configuration",
    "vpn_setup",
    "monitoring_tools",
    "prometheus_grafana",
    "elk_stack",
    "incident_management"
  ],

  // ===== CYBERSECURITY =====
  "cybersecurity": [
    "cybersecurity_fundamentals",
    "network_security",
    "application_security",
    "cloud_security",
    "api_security",
    "cryptography_basics",
    "encryption_standards",
    "secure_coding",
    "input_validation",
    "authentication_security",
    "session_security",
    "oauth_openid",
    "saml",
    "mfa_implementation",
    "vulnerability_management"
  ],

  "ethical_hacking": [
    "hacking_fundamentals",
    "penetration_testing",
    "reconnaissance",
    "scanning_enumeration",
    "vulnerability_assessment",
    "exploitation_techniques",
    "privilege_escalation",
    "post_exploitation",
    "lateral_movement",
    "data_exfiltration",
    "web_app_hacking",
    "network_hacking",
    "wireless_hacking",
    "mobile_hacking",
    "lfi_rfi_vulnerabilities",
    "sql_injection",
    "xss_attacks",
    "csrf_vulnerabilities",
    "xxe_attacks",
    "deserialization_attacks"
  ],

  "advanced_security": [
    "reverse_engineering",
    "malware_analysis",
    "digital_forensics",
    "incident_response",
    "threat_hunting",
    "red_teaming",
    "blue_teaming",
    "siem_tools",
    "intrusion_detection",
    "bug_bounty_programs",
    "security_certifications_prep",
    "compliance_standards",
    "gdpr_ccpa",
    "iso_27001"
  ],

  // ===== DESIGN & CREATIVE =====
  "ui_ux_design": [
    "design_fundamentals",
    "color_theory",
    "typography",
    "layout_principles",
    "grid_systems",
    "ui_kit_creation",
    "design_systems",
    "wireframing",
    "prototyping",
    "user_research",
    "usability_testing",
    "accessibility_design",
    "responsive_design",
    "mobile_first_design",
    "dark_mode_design",
    "design_thinking",
    "figma_advanced",
    "adobe_xd",
    "sketch"
  ],

  "graphic_design": [
    "graphic_design_basics",
    "branding_identity",
    "logo_design",
    "packaging_design",
    "print_design",
    "poster_design",
    "flyer_design",
    "business_card_design",
    "illustration",
    "vector_graphics",
    "adobe_illustrator",
    "adobe_photoshop",
    "adobe_indesign",
    "affinity_designer",
    "corel_draw",
    "canva"
  ],

  "animation_motion": [
    "animation_basics",
    "2d_animation",
    "3d_animation",
    "motion_graphics",
    "keyframe_animation",
    "character_animation",
    "effects_animation",
    "transition_design",
    "micro_interactions",
    "lottie_animations",
    "after_effects",
    "adobe_animate",
    "blender_animation",
    "three_js",
    "babylon_js"
  ],

  "3d_design": [
    "3d_modeling",
    "blender_basics",
    "blender_advanced",
    "3ds_max",
    "maya",
    "zbrush",
    "sculpting",
    "texturing_materials",
    "lighting_rendering",
    "uv_mapping",
    "rigging_animation",
    "game_asset_creation",
    "3d_printing",
    "cad_basics",
    "autocad"
  ],

  "web_design": [
    "web_design_principles",
    "website_layout",
    "navigation_design",
    "landing_page_design",
    "ecommerce_design",
    "portfolio_website",
    "blog_design",
    "cms_design",
    "web_design_trends",
    "conversion_optimization",
    "ab_testing_design"
  ],

  "creative_content": [
    "content_creation",
    "copywriting",
    "storytelling",
    "visual_storytelling",
    "infographic_design",
    "data_visualization",
    "editorial_design",
    "publication_design"
  ],

  // ===== DATA SCIENCE & AI/ML =====
  "data_science": [
    "data_analysis",
    "statistics_basics",
    "probability",
    "descriptive_statistics",
    "inferential_statistics",
    "data_visualization",
    "exploratory_data_analysis",
    "data_cleaning",
    "feature_engineering",
    "data_preprocessing",
    "sql_for_analysis",
    "excel_advanced",
    "pandas",
    "numpy",
    "scipy"
  ],

  "machine_learning": [
    "ml_fundamentals",
    "supervised_learning",
    "linear_regression",
    "logistic_regression",
    "decision_trees",
    "random_forest",
    "support_vector_machines",
    "ensemble_methods",
    "unsupervised_learning",
    "clustering",
    "kmeans",
    "hierarchical_clustering",
    "dimensionality_reduction",
    "pca",
    "regression_analysis",
    "classification",
    "anomaly_detection",
    "reinforcement_learning",
    "scikit_learn",
    "model_evaluation",
    "cross_validation",
    "hyperparameter_tuning"
  ],

  "deep_learning": [
    "neural_networks_basics",
    "perceptrons",
    "mlps",
    "backpropagation",
    "activation_functions",
    "cnn_convolutional",
    "rnn_recurrent",
    "lstm",
    "gru",
    "transformers",
    "attention_mechanism",
    "bert",
    "gpt_models",
    "autoencoder",
    "gan_generative",
    "tensorflow",
    "pytorch",
    "keras",
    "deep_learning_optimization"
  ],

  "nlp_language": [
    "nlp_fundamentals",
    "text_preprocessing",
    "tokenization",
    "stemming_lemmatization",
    "pos_tagging",
    "ner_named_entity",
    "sentiment_analysis",
    "text_classification",
    "machine_translation",
    "question_answering",
    "text_summarization",
    "chatbot_development",
    "language_models",
    "word_embeddings",
    "word2vec",
    "glove",
    "fasttext",
    "spacy",
    "nltk"
  ],

  "computer_vision": [
    "cv_fundamentals",
    "image_processing",
    "filtering_kernels",
    "edge_detection",
    "feature_extraction",
    "image_segmentation",
    "object_detection",
    "face_recognition",
    "pose_estimation",
    "optical_flow",
    "yolo",
    "rcnn",
    "ssd",
    "opencv",
    "image_classification"
  ],

  "big_data": [
    "big_data_fundamentals",
    "hadoop",
    "mapreduce",
    "spark",
    "scala_spark",
    "hive",
    "pig",
    "kafka",
    "data_pipeline",
    "etl_processes",
    "data_warehouse",
    "data_lake",
    "snowflake",
    "dbt"
  ],

  "ai_engineering": [
    "gen_ai_fundamentals",
    "large_language_models",
    "prompt_engineering",
    "fine_tuning",
    "retrieval_augmented_generation",
    "vector_databases",
    "pinecone",
    "chroma",
    "faiss",
    "ai_applications",
    "responsible_ai",
    "ai_ethics",
    "bias_fairness",
    "model_interpretability",
    "explainable_ai"
  ],

  // ===== IT & SOFTWARE FUNDAMENTALS =====
  "computer_fundamentals": [
    "digital_logic",
    "boolean_algebra",
    "computer_architecture",
    "cpu_processing",
    "memory_hierarchy",
    "cache_memory",
    "instruction_sets",
    "assembly_language",
    "number_systems",
    "binary_hexadecimal",
    "computer_organization"
  ],

  "operating_systems": [
    "os_fundamentals",
    "process_management",
    "threading",
    "synchronization",
    "deadlock_prevention",
    "memory_management",
    "virtual_memory",
    "paging_segmentation",
    "file_systems",
    "io_management",
    "disk_scheduling",
    "windows_os",
    "macos_fundamentals",
    "unix_basics"
  ],

  "networking": [
    "networking_fundamentals",
    "osi_model",
    "tcpip_stack",
    "ip_addressing",
    "subnetting",
    "routing_protocols",
    "bgp",
    "ospf",
    "rip",
    "switching",
    "vlans",
    "spanning_tree",
    "network_design",
    "bandwidth_management",
    "qos_quality_service",
    "network_troubleshooting",
    "packet_analysis",
    "wireshark"
  ],

  "database_design": [
    "rdbms_fundamentals",
    "normalization",
    "denormalization",
    "schema_design",
    "indexes_performance",
    "query_optimization",
    "transaction_management",
    "acid_properties",
    "backup_recovery",
    "replication_clustering",
    "nosql_databases",
    "document_stores",
    "key_value_stores",
    "time_series_databases",
    "search_engines"
  ],

  "software_architecture": [
    "design_patterns",
    "creational_patterns",
    "singleton_factory",
    "structural_patterns",
    "adapter_decorator",
    "behavioral_patterns",
    "observer_strategy",
    "architectural_patterns",
    "mvc_mvp_mvvm",
    "layered_architecture",
    "hexagonal_architecture",
    "clean_architecture",
    "microservices_architecture",
    "monolithic_architecture",
    "serverless_architecture",
    "event_driven_architecture",
    "cqrs_event_sourcing"
  ],

  "system_design": [
    "scalability_basics",
    "horizontal_vertical_scaling",
    "load_balancing",
    "caching_strategies",
    "cdn_content_delivery",
    "database_sharding",
    "replication_strategies",
    "consistency_availability",
    "cap_theorem",
    "pacelese_theorem",
    "distributed_systems",
    "consensus_algorithms",
    "message_queues",
    "rate_limiting",
    "circuit_breaker",
    "api_gateway",
    "service_mesh"
  ],

  "software_testing": [
    "testing_fundamentals",
    "unit_testing",
    "integration_testing",
    "system_testing",
    "acceptance_testing",
    "regression_testing",
    "smoke_testing",
    "sanity_testing",
    "performance_testing",
    "load_testing",
    "stress_testing",
    "security_testing",
    "penetration_testing",
    "usability_testing",
    "compatibility_testing",
    "test_frameworks",
    "jest",
    "mocha",
    "pytest",
    "junit",
    "selenium",
    "appium",
    "cypress",
    "playwright",
    "test_driven_development",
    "behavior_driven_development"
  ],

  "quality_assurance": [
    "qa_fundamentals",
    "test_planning",
    "test_case_design",
    "boundary_value_analysis",
    "equivalence_partitioning",
    "error_guessing",
    "exploratory_testing",
    "bug_tracking",
    "test_automation",
    "continuous_testing",
    "quality_metrics",
    "defect_analysis"
  ],

  // ===== BUSINESS & MANAGEMENT =====
  "business_fundamentals": [
    "business_basics",
    "business_models",
    "value_proposition",
    "market_analysis",
    "competitive_strategy",
    "swot_analysis",
    "porter_five_forces",
    "business_planning",
    "financial_planning",
    "budgeting",
    "forecasting"
  ],

  "entrepreneurship": [
    "startup_fundamentals",
    "idea_validation",
    "business_plan_creation",
    "market_research",
    "customer_development",
    "mvp_development",
    "fundraising",
    "venture_capital",
    "angel_investing",
    "pitch_deck_creation",
    "product_market_fit",
    "growth_hacking",
    "scaling_startup",
    "startup_culture"
  ],

  "management_leadership": [
    "management_basics",
    "leadership_fundamentals",
    "team_management",
    "conflict_resolution",
    "motivation_engagement",
    "performance_management",
    "delegation",
    "decision_making",
    "critical_thinking",
    "strategic_planning",
    "change_management",
    "organizational_behavior",
    "corporate_governance"
  ],

  "project_management": [
    "pm_fundamentals",
    "project_planning",
    "project_scheduling",
    "resource_management",
    "risk_management",
    "stakeholder_management",
    "project_communication",
    "project_monitoring",
    "agile_methodology",
    "scrum_framework",
    "kanban",
    "lean_principles",
    "six_sigma",
    "waterfall_methodology",
    "pmp_certification",
    "jira_project_tools",
    "asana",
    "monday_com"
  ],

  "product_management": [
    "product_management_basics",
    "product_strategy",
    "roadmap_planning",
    "feature_prioritization",
    "product_requirements",
    "user_stories",
    "product_analytics",
    "metrics_kpis",
    "ab_testing",
    "product_launch",
    "product_lifecycle",
    "competitor_analysis"
  ],

  // ===== FINANCE & INVESTMENT =====
  "finance_investing": [
    "finance_fundamentals",
    "personal_finance",
    "budgeting_saving",
    "debt_management",
    "credit_score",
    "insurance_basics",
    "investment_fundamentals",
    "stocks_basics",
    "bonds_bonds",
    "mutual_funds",
    "etfs",
    "derivatives",
    "options_trading",
    "futures_trading",
    "portfolio_management",
    "diversification",
    "risk_assessment",
    "asset_allocation"
  ],

  "trading_markets": [
    "stock_market_basics",
    "nse_bse_india",
    "trading_fundamentals",
    "day_trading",
    "swing_trading",
    "position_trading",
    "technical_analysis",
    "candlestick_patterns",
    "chart_analysis",
    "indicators_oscillators",
    "fundamental_analysis",
    "company_valuation",
    "financial_ratios",
    "earnings_analysis",
    "forex_trading",
    "currency_pairs",
    "forex_strategy"
  ],

  "cryptocurrency_blockchain": [
    "cryptocurrency_basics",
    "bitcoin_ethereum",
    "altcoins",
    "blockchain_technology",
    "smart_contracts",
    "nft_tokens",
    "defi_decentralized",
    "defi_protocols",
    "yield_farming",
    "staking",
    "crypto_wallets",
    "exchanges",
    "crypto_security",
    "tax_crypto"
  ],

  "accounting_finance": [
    "accounting_basics",
    "double_entry_bookkeeping",
    "journal_ledger",
    "trial_balance",
    "financial_statements",
    "balance_sheet",
    "income_statement",
    "cash_flow_statement",
    "cost_accounting",
    "financial_analysis",
    "ratio_analysis",
    "auditing_basics",
    "tax_preparation",
    "gst_india",
    "income_tax",
    "corporate_tax"
  ],

  // ===== MARKETING & SALES =====
  "digital_marketing": [
    "digital_marketing_basics",
    "marketing_fundamentals",
    "market_segmentation",
    "target_audience",
    "buyer_persona",
    "customer_journey",
    "marketing_funnel",
    "conversion_rate",
    "marketing_automation",
    "marketing_analytics",
    "google_analytics",
    "marketing_tools"
  ],

  "seo_sem": [
    "seo_fundamentals",
    "on_page_seo",
    "off_page_seo",
    "technical_seo",
    "keyword_research",
    "backlink_strategy",
    "sem_pay_per_click",
    "google_ads",
    "facebook_ads",
    "linkedin_ads",
    "conversion_tracking",
    "seo_tools",
    "semrush",
    "ahrefs",
    "moz"
  ],

  "social_media_marketing": [
    "social_media_fundamentals",
    "facebook_marketing",
    "instagram_marketing",
    "tiktok_marketing",
    "linkedin_marketing",
    "twitter_x_marketing",
    "youtube_marketing",
    "pinterest_marketing",
    "snapchat_marketing",
    "social_content_strategy",
    "influencer_marketing",
    "community_management",
    "social_listening",
    "social_analytics"
  ],

  "content_marketing": [
    "content_strategy",
    "blog_marketing",
    "email_marketing",
    "email_campaigns",
    "newsletter",
    "video_marketing",
    "podcast_marketing",
    "webinar_marketing",
    "ebook_creation",
    "whitepaper_creation",
    "case_study_writing",
    "copywriting_conversion",
    "content_calendar",
    "editorial_calendar"
  ],

  "branding_marketing": [
    "branding_fundamentals",
    "brand_strategy",
    "brand_identity",
    "brand_positioning",
    "brand_voice",
    "brand_messaging",
    "logo_branding",
    "brand_guidelines",
    "brand_management",
    "reputation_management",
    "crisis_communication"
  ],

  // ===== INDIAN COMPETITIVE EXAMS =====
  "engineering_entrance": [
    "jee_mains",
    "jee_advanced",
    "jee_mathematics",
    "jee_physics",
    "jee_chemistry",
    "bitsat",
    "vit_entrance",
    "manipal_entrance",
    "srm_entrance",
    "nit_entrance",
    "iiit_entrance"
  ],

  "medical_entrance": [
    "neet_preparation",
    "neet_biology",
    "neet_chemistry",
    "neet_physics",
    "aiims_preparation",
    "jipmer_preparation",
    "aipvt"
  ],

  "civil_service": [
    "upsc_ias_preparation",
    "upsc_prelims",
    "upsc_mains",
    "upsc_interview",
    "upsc_gs_general_studies",
    "upsc_history",
    "upsc_geography",
    "upsc_politics_constitution",
    "upsc_economy",
    "upsc_science_technology",
    "upsc_environment",
    "upsc_international_relations",
    "upsc_optional_subjects",
    "upsc_essay_writing",
    "state_pcs_exams",
    "state_ias_preparation"
  ],

  "management_entrance": [
    "cat_preparation",
    "cat_quantitative",
    "cat_verbal",
    "cat_logical_reasoning",
    "xat_preparation",
    "snap_preparation",
    "iift_preparation",
    "mat_preparation",
    "cmat_preparation",
    "gmat_preparation",
    "mba_entrance"
  ],

  "other_competitive_exams": [
    "gate_preparation",
    "gate_cse",
    "gate_ece",
    "gate_mechanical",
    "gate_civil",
    "ssc_cgl",
    "ssc_chsl",
    "ssc_mts",
    "ssc_je",
    "banking_ibps_po",
    "banking_ibps_clerk",
    "banking_sbi_po",
    "banking_sbi_clerk",
    "rrb_ntpc",
    "rrb_asm",
    "rrb_je",
    "rrb_group_d",
    "afcat_preparation",
    "cds_preparation",
    "nda_preparation",
    "clat_law_entrance",
    "ailet_law",
    "nimcet_nit_mca",
    "iiser_entrance",
    "kvpy_scholarship"
  ],

  // ===== LANGUAGES & COMMUNICATION =====
  "english_language": [
    "english_fundamentals",
    "grammar_basics",
    "vocabulary_building",
    "spelling_punctuation",
    "reading_comprehension",
    "writing_skills",
    "essay_writing",
    "paragraph_writing",
    "description_writing",
    "letter_writing",
    "email_writing",
    "public_speaking",
    "presentation_skills",
    "interview_preparation",
    "toefl_preparation",
    "ielts_preparation",
    "spoken_english",
    "business_english",
    "english_literature"
  ],

  "indian_languages": [
    "hindi_language",
    "sanskrit_language",
    "bengali_basics",
    "tamil_basics",
    "telugu_basics",
    "kannada_basics",
    "malayalam_basics",
    "punjabi_basics",
    "gujarati_basics",
    "marathi_basics",
    "urdu_basics"
  ],

  "foreign_languages": [
    "spanish_basics",
    "spanish_advanced",
    "french_basics",
    "french_advanced",
    "german_basics",
    "german_advanced",
    "japanese_basics",
    "japanese_advanced",
    "mandarin_chinese",
    "korean_basics",
    "arabic_basics",
    "portuguese_basics",
    "russian_basics",
    "italian_basics"
  ],

  "communication_skills": [
    "communication_fundamentals",
    "verbal_communication",
    "nonverbal_communication",
    "active_listening",
    "presentation_skills",
    "public_speaking",
    "negotiation_skills",
    "conflict_resolution",
    "assertiveness",
    "empathy",
    "professional_etiquette",
    "business_communication",
    "technical_writing",
    "report_writing",
    "documentation"
  ],

  // ===== SCIENCE & TECHNOLOGY =====
  "physics": [
    "physics_fundamentals",
    "mechanics",
    "kinematics",
    "dynamics",
    "work_energy",
    "power_work",
    "momentum_collision",
    "gravitation",
    "rotational_motion",
    "simple_harmonic_motion",
    "waves_oscillations",
    "sound_acoustics",
    "optics_light",
    "electricity",
    "electrostatics",
    "current_electricity",
    "magnetism",
    "electromagnetic_induction",
    "alternating_current",
    "thermodynamics",
    "heat_temperature",
    "modern_physics",
    "atomic_physics",
    "nuclear_physics",
    "quantum_mechanics",
    "relativity",
    "astrophysics"
  ],

  "chemistry": [
    "chemistry_fundamentals",
    "atomic_structure",
    "periodic_table",
    "chemical_bonding",
    "molecular_structure",
    "balancing_equations",
    "stoichiometry",
    "thermochemistry",
    "kinetics_reaction_rates",
    "equilibrium",
    "acid_base_chemistry",
    "redox_reactions",
    "electrochemistry",
    "organic_chemistry",
    "inorganic_chemistry",
    "physical_chemistry",
    "coordination_chemistry",
    "qualitative_analysis",
    "quantitative_analysis",
    "laboratory_techniques"
  ],

  "biology": [
    "biology_fundamentals",
    "cell_biology",
    "cell_structure",
    "cell_division",
    "genetics_heredity",
    "dna_rna",
    "protein_synthesis",
    "evolution",
    "ecology",
    "plant_biology",
    "animal_biology",
    "human_anatomy",
    "human_physiology",
    "digestive_system",
    "circulatory_system",
    "respiratory_system",
    "nervous_system",
    "endocrine_system",
    "immune_system",
    "microbiology",
    "biotechnology",
    "genetic_engineering"
  ],

  "mathematics": [
    "math_fundamentals",
    "arithmetic",
    "number_system",
    "fractions_decimals",
    "percentages",
    "ratio_proportion",
    "algebra_basics",
    "linear_equations",
    "quadratic_equations",
    "polynomials",
    "factorization",
    "indices_surds",
    "logarithms",
    "sequences_series",
    "arithmetic_progression",
    "geometric_progression",
    "trigonometry",
    "trigonometric_ratios",
    "trigonometric_equations",
    "geometry",
    "coordinate_geometry",
    "calculus",
    "limits_continuity",
    "differentiation",
    "integration",
    "applications_calculus",
    "statistics_math",
    "probability_math",
    "permutation_combination",
    "set_theory",
    "linear_algebra",
    "matrices_determinants",
    "vectors"
  ],

  // ===== DESIGN & CREATIVE CONTENT =====
  "art_basics": [
    "drawing_fundamentals",
    "sketching_techniques",
    "pencil_drawing",
    "charcoal_drawing",
    "ink_drawing",
    "pastel_drawing",
    "painting_watercolor",
    "acrylic_painting",
    "oil_painting",
    "painting_techniques",
    "color_mixing",
    "perspective_drawing",
    "anatomy_figure_drawing",
    "portrait_drawing",
    "landscape_drawing",
    "still_life_drawing"
  ],

  "digital_art": [
    "digital_art_basics",
    "digital_painting",
    "procreate",
    "clip_studio_paint",
    "krita",
    "pixel_art",
    "digital_illustration",
    "concept_art",
    "character_design",
    "environment_design",
    "storyboarding"
  ],

  "photography": [
    "photography_fundamentals",
    "camera_mechanics",
    "aperture_shutter_iso",
    "exposure",
    "composition_rules",
    "lighting_photography",
    "portrait_photography",
    "landscape_photography",
    "wildlife_photography",
    "street_photography",
    "macro_photography",
    "product_photography",
    "event_photography",
    "photo_processing",
    "lightroom",
    "photoshop_retouching"
  ],

  "videography_editing": [
    "videography_basics",
    "video_equipment",
    "shot_composition",
    "video_lighting",
    "audio_recording",
    "video_editing_fundamentals",
    "premiere_pro",
    "final_cut_pro",
    "davinci_resolve",
    "editing_techniques",
    "color_grading",
    "motion_graphics_video",
    "sound_design",
    "music_selection",
    "video_effects",
    "video_transitions"
  ],

  // ===== MUSIC & PERFORMING ARTS =====
  "music_fundamentals": [
    "music_basics",
    "music_theory",
    "notes_scales",
    "chords_harmony",
    "rhythm_time_signature",
    "melody_composition",
    "music_notation",
    "ear_training",
    "sight_reading",
    "music_history",
    "classical_music",
    "jazz_music",
    "blues_music"
  ],

  "musical_instruments": [
    "guitar_playing",
    "acoustic_guitar",
    "electric_guitar",
    "guitar_chords",
    "guitar_techniques",
    "piano_keyboard",
    "piano_basics",
    "piano_theory",
    "drums_percussion",
    "bass_guitar",
    "ukulele",
    "violin",
    "flute",
    "harmonium",
    "tabla",
    "sitar"
  ],

  "vocal_music": [
    "singing_fundamentals",
    "voice_training",
    "vocal_techniques",
    "breath_control",
    "pitch_control",
    "vocal_warm_ups",
    "song_interpretation",
    "karaoke",
    "professional_singing"
  ],

  "music_production": [
    "music_production_basics",
    "daw_digital_audio",
    "ableton_live",
    "fl_studio",
    "logic_pro",
    "studio_setup",
    "recording_techniques",
    "mixing_mastering",
    "sound_design",
    "beat_making",
    "music_arrangement",
    "production_workflow"
  ],

  // ===== GAMING & GAME DEVELOPMENT =====
  "game_development": [
    "game_dev_fundamentals",
    "game_design_principles",
    "game_genres",
    "game_mechanics",
    "level_design",
    "narrative_design",
    "game_economy",
    "game_engines",
    "unity_basics",
    "unity_advanced",
    "unreal_engine_4",
    "unreal_engine_5",
    "godot_engine",
    "cocos_creator",
    "game_physics",
    "game_ai",
    "pathfinding_ai",
    "behavior_trees",
    "game_networking",
    "multiplayer_games",
    "game_monetization",
    "live_service_games"
  ],

  "esports_gaming": [
    "esports_fundamentals",
    "competitive_gaming",
    "fps_games",
    "moba_games",
    "rts_games",
    "fighting_games",
    "esports_training",
    "game_streaming",
    "twitch_streaming",
    "youtube_gaming",
    "commentating",
    "esports_management"
  ],

  // ===== BLOCKCHAIN & WEB3 =====
  "blockchain_web3": [
    "blockchain_fundamentals",
    "distributed_ledger",
    "consensus_mechanisms",
    "proof_of_work",
    "proof_of_stake",
    "smart_contracts",
    "solidity_programming",
    "ethereum_development",
    "web3_development",
    "web3_js",
    "ethers_js",
    "defi_development",
    "nft_development",
    "dao_development",
    "ipfs_storage",
    "layer2_scaling",
    "rollups",
    "sidechains",
    "cross_chain_bridges"
  ],

  "smart_contracts": [
    "solidity_basics",
    "solidity_advanced",
    "vyper",
    "rust_blockchain",
    "contract_security",
    "contract_audit",
    "contract_testing",
    "hardhat_framework",
    "truffle_framework",
    "foundry",
    "contract_deployment"
  ],

  // ===== SOFT SKILLS & PROFESSIONAL DEVELOPMENT =====
  "soft_skills": [
    "time_management",
    "productivity_hacks",
    "goal_setting",
    "prioritization",
    "focus_concentration",
    "critical_thinking",
    "problem_solving",
    "creativity_innovation",
    "adaptability",
    "flexibility",
    "resilience",
    "stress_management",
    "emotional_intelligence",
    "self_awareness",
    "empathy_compassion",
    "confidence_building",
    "assertiveness",
    "accountability",
    "responsibility"
  ],

  "career_development": [
    "career_planning",
    "resume_writing",
    "cv_building",
    "cover_letter",
    "job_search_strategies",
    "interview_skills",
    "salary_negotiation",
    "career_transition",
    "professional_networking",
    "linkedin_profile",
    "personal_branding",
    "freelancing_basics",
    "upskilling_reskilling",
    "certifications_value",
    "mentorship"
  ],

  "personal_development": [
    "mindfulness_meditation",
    "meditation_techniques",
    "stress_relief",
    "anxiety_management",
    "work_life_balance",
    "habit_formation",
    "productivity_systems",
    "learning_strategies",
    "reading_comprehension",
    "note_taking_techniques",
    "memory_techniques",
    "active_learning",
    "metacognition",
    "growth_mindset"
  ],

  "team_collaboration": [
    "teamwork_fundamentals",
    "collaboration_skills",
    "group_dynamics",
    "feedback_giving",
    "feedback_receiving",
    "difficult_conversations",
    "conflict_resolution_team",
    "trust_building",
    "inclusion_diversity",
    "remote_collaboration",
    "virtual_team_management",
    "cross_functional_teams"
  ],

  // ===== PROFESSIONAL CERTIFICATIONS & SKILLS =====
  "it_certifications": [
    "microsoft_certifications",
    "azure_certifications",
    "aws_certifications",
    "google_cloud_certifications",
    "cisco_certifications",
    "comptia_certifications",
    "rhel_certifications",
    "linux_certifications",
    "virtualization_certifications",
    "cloud_certifications",
    "security_certifications",
    "cissp",
    "ceh_ethical_hacking",
    "oscp",
    "ccna",
    "ccnp"
  ],

  "professional_skills": [
    "quality_assurance_skills",
    "business_analysis",
    "data_analysis_professional",
    "research_methodology",
    "grant_writing",
    "proposal_writing",
    "presentation_design",
    "infographic_creation",
    "customer_service",
    "sales_skills",
    "client_relationship",
    "vendor_management"
  ],

  // ===== EDUCATION & SKILL DEVELOPMENT =====
  "academic_support": [
    "study_skills",
    "exam_preparation",
    "note_taking",
    "test_anxiety",
    "academic_writing",
    "research_paper_writing",
    "dissertation_thesis",
    "academic_integrity",
    "plagiarism_prevention",
    "citation_styles",
    "mla_format",
    "apa_format",
    "chicago_style"
  ],

  "specialized_skills": [
    "spreadsheet_advanced",
    "spreadsheet_formulas",
    "data_analysis_excel",
    "pivot_tables",
    "vlookup_xlookup",
    "power_query",
    "data_visualization_excel",
    "vba_macros",
    "presentation_software",
    "powerpoint_advanced",
    "keynote_mac",
    "google_slides",
    "desktop_publishing",
    "office_productivity"
  ]
};