export const mockUsers = [
  {
    _id: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@example.com',
    phone: '+1234567890',
    dateOfBirth: '1990-05-15',
    gender: 'Male',
    isEmailVerified: true,
    isPhoneVerified: true,
    isKYCVerified: true,
    isActive: true,
    enrolledCourses: [
      {
        courseId: 'c1',
        courseName: 'React Advanced Patterns',
        enrollmentDate: '2024-01-15',
        completionPercentage: 75,
        isCompleted: false,
      },
      {
        courseId: 'c2',
        courseName: 'Node.js Masterclass',
        enrollmentDate: '2024-02-01',
        completionPercentage: 100,
        isCompleted: true,
      },
    ],
    learningProgress: {
      totalCoursesEnrolled: 2,
      totalCoursesCompleted: 1,
      totalLearningHours: 45,
      certificates: 1,
      averageRating: 4.5,
    },
    createdAt: '2024-01-10T08:30:00Z',
    lastLogin: '2026-02-05T10:15:00Z',
    address: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'USA',
    },
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      courseUpdates: true,
      promotionalEmails: true,
      language: 'en',
    },
  },
  {
    _id: '2',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.j@example.com',
    phone: '+1234567891',
    dateOfBirth: '1992-08-22',
    gender: 'Female',
    isEmailVerified: true,
    isPhoneVerified: true,
    isKYCVerified: false,
    isActive: true,
    enrolledCourses: [
      {
        courseId: 'c3',
        courseName: 'Python for Data Science',
        enrollmentDate: '2024-01-20',
        completionPercentage: 45,
        isCompleted: false,
      },
    ],
    learningProgress: {
      totalCoursesEnrolled: 1,
      totalCoursesCompleted: 0,
      totalLearningHours: 22,
      certificates: 0,
      averageRating: 0,
    },
    createdAt: '2024-01-18T09:20:00Z',
    lastLogin: '2026-02-04T14:30:00Z',
    address: {
      street: '456 Oak Ave',
      city: 'Los Angeles',
      state: 'CA',
      postalCode: '90001',
      country: 'USA',
    },
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      courseUpdates: true,
      promotionalEmails: false,
      language: 'en',
    },
  },
  {
    _id: '3',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@example.com',
    phone: '+1234567892',
    dateOfBirth: '1988-12-10',
    gender: 'Male',
    isEmailVerified: true,
    isPhoneVerified: false,
    isKYCVerified: true,
    isActive: true,
    enrolledCourses: [
      {
        courseId: 'c4',
        courseName: 'Full Stack Web Development',
        enrollmentDate: '2023-11-05',
        completionPercentage: 100,
        isCompleted: true,
      },
      {
        courseId: 'c5',
        courseName: 'DevOps Essentials',
        enrollmentDate: '2024-01-10',
        completionPercentage: 30,
        isCompleted: false,
      },
    ],
    learningProgress: {
      totalCoursesEnrolled: 2,
      totalCoursesCompleted: 1,
      totalLearningHours: 65,
      certificates: 1,
      averageRating: 5.0,
    },
    createdAt: '2023-10-28T11:00:00Z',
    lastLogin: '2026-02-06T09:00:00Z',
    address: {
      street: '789 Elm St',
      city: 'Chicago',
      state: 'IL',
      postalCode: '60601',
      country: 'USA',
    },
    preferences: {
      emailNotifications: true,
      smsNotifications: false,
      courseUpdates: true,
      promotionalEmails: true,
      language: 'en',
    },
  },
  {
    _id: '4',
    firstName: 'Emily',
    lastName: 'Rodriguez',
    email: 'emily.r@example.com',
    phone: '+1234567893',
    dateOfBirth: '1995-03-18',
    gender: 'Female',
    isEmailVerified: true,
    isPhoneVerified: true,
    isKYCVerified: true,
    isActive: false,
    enrolledCourses: [],
    learningProgress: {
      totalCoursesEnrolled: 0,
      totalCoursesCompleted: 0,
      totalLearningHours: 0,
      certificates: 0,
      averageRating: 0,
    },
    createdAt: '2024-02-01T13:45:00Z',
    address: {
      street: '321 Pine Rd',
      city: 'Miami',
      state: 'FL',
      postalCode: '33101',
      country: 'USA',
    },
    preferences: {
      emailNotifications: false,
      smsNotifications: false,
      courseUpdates: false,
      promotionalEmails: false,
      language: 'en',
    },
  },
  {
    _id: '5',
    firstName: 'David',
    lastName: 'Kim',
    email: 'david.kim@example.com',
    phone: '+1234567894',
    dateOfBirth: '1991-07-25',
    gender: 'Male',
    isEmailVerified: true,
    isPhoneVerified: true,
    isKYCVerified: true,
    isActive: true,
    enrolledCourses: [
      {
        courseId: 'c6',
        courseName: 'Machine Learning Fundamentals',
        enrollmentDate: '2024-01-25',
        completionPercentage: 60,
        isCompleted: false,
      },
    ],
    learningProgress: {
      totalCoursesEnrolled: 1,
      totalCoursesCompleted: 0,
      totalLearningHours: 35,
      certificates: 0,
      averageRating: 4.8,
    },
    createdAt: '2024-01-22T16:20:00Z',
    lastLogin: '2026-02-05T18:45:00Z',
    address: {
      street: '555 Maple Dr',
      city: 'Seattle',
      state: 'WA',
      postalCode: '98101',
      country: 'USA',
    },
    preferences: {
      emailNotifications: true,
      smsNotifications: true,
      courseUpdates: true,
      promotionalEmails: true,
      language: 'en',
    },
  },
];
