
export const mockCourses = [
  {
    _id: '1',
    title: 'Advanced React Patterns & Best Practices',
    description: 'Master advanced React concepts including hooks, context, performance optimization, and modern design patterns. Learn to build scalable and maintainable React applications.',
    shortDescription: 'Learn advanced React patterns and build production-ready applications',
    instructor: {
      _id: '1',
      name: 'Dr. Sarah Williams',
    },
    category: 'programming',
    level: 'advanced',
    language: 'English',
    price: 149.99,
    currency: 'USD',
    discountPrice: 99.99,
    totalModules: 12,
    totalLessons: 87,
    totalDuration: 1440,
    status: 'published',
    isPublished: true,
    publishedAt: '2024-01-15T10:00:00Z',
    enrolledCount: 543,
    rating: 4.8,
    totalReviews: 127,
    learningOutcomes: [
      'Master advanced React hooks and custom hooks',
      'Implement complex state management patterns',
      'Optimize React application performance',
      'Build reusable component libraries',
    ],
    prerequisites: [
      'Basic knowledge of React and JavaScript',
      'Understanding of ES6+ features',
      'Familiarity with npm and package management',
    ],
    tags: ['react', 'javascript', 'web development', 'frontend'],
    isFree: false,
    certificateEnabled: true,
    createdAt: '2023-12-01T08:00:00Z',
  },
  {
    _id: '2',
    title: 'Machine Learning with Python - Complete Bootcamp',
    description: 'Comprehensive course covering machine learning fundamentals, algorithms, and practical applications using Python, scikit-learn, and TensorFlow.',
    shortDescription: 'Complete machine learning course from basics to advanced',
    instructor: {
      _id: '2',
      name: 'Prof. Michael Chen',
    },
    category: 'data-science',
    level: 'intermediate',
    language: 'English',
    price: 199.99,
    currency: 'USD',
    totalModules: 15,
    totalLessons: 112,
    totalDuration: 2160,
    status: 'published',
    isPublished: true,
    publishedAt: '2024-01-20T09:00:00Z',
    enrolledCount: 789,
    rating: 4.9,
    totalReviews: 234,
    learningOutcomes: [
      'Understand machine learning algorithms',
      'Build and train ML models',
      'Work with real-world datasets',
      'Deploy ML models to production',
    ],
    prerequisites: [
      'Python programming basics',
      'Basic understanding of statistics',
      'Linear algebra fundamentals',
    ],
    tags: ['machine learning', 'python', 'data science', 'ai'],
    isFree: false,
    certificateEnabled: true,
    createdAt: '2023-12-10T10:00:00Z',
  },
  {
    _id: '3',
    title: 'UI/UX Design Masterclass - Figma to Reality',
    description: 'Learn modern UI/UX design principles and create stunning user interfaces using Figma. From wireframes to high-fidelity prototypes.',
    shortDescription: 'Master UI/UX design with Figma and design thinking',
    instructor: {
      _id: '3',
      name: 'Jessica Martinez',
    },
    category: 'design',
    level: 'beginner',
    language: 'English',
    price: 89.99,
    currency: 'USD',
    discountPrice: 59.99,
    totalModules: 8,
    totalLessons: 64,
    totalDuration: 960,
    status: 'published',
    isPublished: true,
    publishedAt: '2024-01-10T11:00:00Z',
    enrolledCount: 432,
    rating: 4.7,
    totalReviews: 98,
    learningOutcomes: [
      'Master Figma design tools',
      'Create professional UI/UX designs',
      'Understand user-centered design',
      'Build interactive prototypes',
    ],
    prerequisites: [
      'Basic computer skills',
      'Interest in design',
    ],
    tags: ['ui/ux', 'figma', 'design', 'prototyping'],
    isFree: false,
    certificateEnabled: true,
    createdAt: '2023-12-05T09:00:00Z',
  },
  {
    _id: '4',
    title: 'Cybersecurity Fundamentals & Ethical Hacking',
    description: 'Learn cybersecurity principles, network security, penetration testing, and ethical hacking techniques to protect systems and data.',
    shortDescription: 'Become a cybersecurity professional',
    instructor: {
      _id: '4',
      name: 'David Thompson',
    },
    category: 'programming',
    level: 'intermediate',
    language: 'English',
    price: 179.99,
    currency: 'USD',
    totalModules: 10,
    totalLessons: 76,
    totalDuration: 1320,
    status: 'published',
    isPublished: true,
    publishedAt: '2024-01-25T10:00:00Z',
    enrolledCount: 321,
    rating: 4.9,
    totalReviews: 87,
    learningOutcomes: [
      'Understand cybersecurity principles',
      'Perform penetration testing',
      'Secure networks and systems',
      'Identify and fix vulnerabilities',
    ],
    prerequisites: [
      'Basic networking knowledge',
      'Linux command line basics',
      'Understanding of computer systems',
    ],
    tags: ['cybersecurity', 'ethical hacking', 'security', 'networking'],
    isFree: false,
    certificateEnabled: true,
    createdAt: '2023-12-20T11:00:00Z',
  },
  {
    _id: '5',
    title: 'Introduction to Programming - Free Course',
    description: 'Perfect for beginners! Learn programming fundamentals with JavaScript. No prior experience required.',
    shortDescription: 'Start your programming journey today',
    instructor: {
      _id: '1',
      name: 'Dr. Sarah Williams',
    },
    category: 'programming',
    level: 'beginner',
    language: 'English',
    price: 0,
    currency: 'USD',
    totalModules: 6,
    totalLessons: 42,
    totalDuration: 480,
    status: 'published',
    isPublished: true,
    publishedAt: '2024-02-01T08:00:00Z',
    enrolledCount: 1254,
    rating: 4.6,
    totalReviews: 342,
    learningOutcomes: [
      'Learn programming basics',
      'Understand variables and data types',
      'Write simple programs',
      'Build a foundation for advanced topics',
    ],
    prerequisites: [],
    tags: ['programming', 'javascript', 'beginner', 'free'],
    isFree: true,
    certificateEnabled: true,
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    _id: '6',
    title: 'Full Stack Web Development Bootcamp',
    description: 'Become a full-stack developer by learning HTML, CSS, JavaScript, React, Node.js, Express, and MongoDB. Build real-world projects.',
    shortDescription: 'Complete full-stack web development course',
    instructor: {
      _id: '1',
      name: 'Dr. Sarah Williams',
    },
    category: 'programming',
    level: 'intermediate',
    language: 'English',
    price: 249.99,
    currency: 'USD',
    discountPrice: 179.99,
    totalModules: 20,
    totalLessons: 156,
    totalDuration: 3000,
    status: 'draft',
    isPublished: false,
    enrolledCount: 0,
    rating: 0,
    totalReviews: 0,
    learningOutcomes: [
      'Build full-stack web applications',
      'Master frontend and backend development',
      'Work with databases',
      'Deploy applications to cloud',
    ],
    prerequisites: [
      'Basic HTML, CSS knowledge',
      'JavaScript fundamentals',
    ],
    tags: ['full-stack', 'web development', 'react', 'node.js'],
    isFree: false,
    certificateEnabled: true,
    createdAt: '2024-02-01T12:00:00Z',
  },
];
