export const mockInstructors = [
  {
    _id: '1',
    firstName: 'Dr. Sarah',
    lastName: 'Williams',
    email: 'sarah.williams@greedacademy.com',
    phone: '+1234567900',
    bio: 'PhD in Computer Science with 15 years of teaching experience in web development and software engineering.',
    specialization: ['web_development', 'software_engineering', 'cloud_computing'],
    yearsOfExperience: 15,
    totalStudentsTeaching: 1250,
    totalCourses: 8,
    totalLiveClasses: 45,
    rating: {
      averageRating: 4.9,
      totalReviews: 327,
    },
    isEmailVerified: true,
    isPhoneVerified: true,
    isDocumentsVerified: true,
    isKYCVerified: true,
    isActive: true,
    isSuspended: false,
    createdAt: '2023-01-15T08:00:00Z',
    lastLogin: '2026-02-06T07:30:00Z',
    qualifications: [
      {
        degree: 'PhD in Computer Science',
        institution: 'Stanford University',
        yearOfCompletion: 2010,
      },
      {
        degree: 'MS in Software Engineering',
        institution: 'MIT',
        yearOfCompletion: 2005,
      },
    ],
    earnings: {
      totalEarnings: 125000,
      pendingPayment: 15000,
      paidAmount: 110000,
      currency: 'USD',
    },
    preferences: {
      emailNotifications: true,
      classReminders: true,
      studentUpdates: true,
      language: 'en',
      timezone: 'America/New_York',
    },
  },
  {
    _id: '2',
    firstName: 'Prof. Michael',
    lastName: 'Chen',
    email: 'michael.chen@greedacademy.com',
    phone: '+1234567901',
    bio: 'Data Science expert with focus on Machine Learning and AI. Former lead data scientist at Google.',
    specialization: ['data_science', 'machine_learning', 'artificial_intelligence'],
    yearsOfExperience: 12,
    totalStudentsTeaching: 980,
    totalCourses: 6,
    totalLiveClasses: 38,
    rating: {
      averageRating: 4.8,
      totalReviews: 215,
    },
    isEmailVerified: true,
    isPhoneVerified: true,
    isDocumentsVerified: true,
    isKYCVerified: true,
    isActive: true,
    isSuspended: false,
    createdAt: '2023-03-20T10:00:00Z',
    lastLogin: '2026-02-05T16:20:00Z',
    qualifications: [
      {
        degree: 'PhD in Data Science',
        institution: 'UC Berkeley',
        yearOfCompletion: 2012,
      },
    ],
    earnings: {
      totalEarnings: 98000,
      pendingPayment: 12000,
      paidAmount: 86000,
      currency: 'USD',
    },
    preferences: {
      emailNotifications: true,
      classReminders: true,
      studentUpdates: true,
      language: 'en',
      timezone: 'America/Los_Angeles',
    },
  },
  {
    _id: '3',
    firstName: 'Jessica',
    lastName: 'Martinez',
    email: 'jessica.martinez@greedacademy.com',
    phone: '+1234567902',
    bio: 'UI/UX Designer and Frontend Developer. Specializes in modern design systems and React development.',
    specialization: ['design', 'web_development', 'mobile_app_development'],
    yearsOfExperience: 8,
    totalStudentsTeaching: 756,
    totalCourses: 5,
    totalLiveClasses: 29,
    rating: {
      averageRating: 4.7,
      totalReviews: 189,
    },
    isEmailVerified: true,
    isPhoneVerified: true,
    isDocumentsVerified: true,
    isKYCVerified: false,
    isActive: true,
    isSuspended: false,
    createdAt: '2023-05-10T14:30:00Z',
    lastLogin: '2026-02-04T11:15:00Z',
    qualifications: [
      {
        degree: 'MS in Human-Computer Interaction',
        institution: 'Carnegie Mellon University',
        yearOfCompletion: 2016,
      },
    ],
    earnings: {
      totalEarnings: 67000,
      pendingPayment: 8500,
      paidAmount: 58500,
      currency: 'USD',
    },
    preferences: {
      emailNotifications: true,
      classReminders: false,
      studentUpdates: true,
      language: 'en',
      timezone: 'America/Chicago',
    },
  },
  {
    _id: '4',
    firstName: 'David',
    lastName: 'Thompson',
    email: 'david.thompson@greedacademy.com',
    phone: '+1234567903',
    bio: 'Cybersecurity expert and ethical hacker. Certified CISSP and CEH.',
    specialization: ['cybersecurity', 'devops', 'cloud_computing'],
    yearsOfExperience: 10,
    totalStudentsTeaching: 543,
    totalCourses: 4,
    totalLiveClasses: 22,
    rating: {
      averageRating: 4.9,
      totalReviews: 142,
    },
    isEmailVerified: true,
    isPhoneVerified: false,
    isDocumentsVerified: true,
    isKYCVerified: true,
    isActive: true,
    isSuspended: false,
    createdAt: '2023-07-05T09:00:00Z',
    lastLogin: '2026-02-03T13:45:00Z',
    qualifications: [
      {
        degree: 'MS in Cybersecurity',
        institution: 'Georgia Tech',
        yearOfCompletion: 2014,
      },
    ],
    earnings: {
      totalEarnings: 54000,
      pendingPayment: 6000,
      paidAmount: 48000,
      currency: 'USD',
    },
    preferences: {
      emailNotifications: true,
      classReminders: true,
      studentUpdates: true,
      language: 'en',
      timezone: 'America/Denver',
    },
  },
  {
    _id: '5',
    firstName: 'Amanda',
    lastName: 'Foster',
    email: 'amanda.foster@greedacademy.com',
    phone: '+1234567904',
    bio: 'Blockchain developer and cryptocurrency enthusiast. 6 years in decentralized applications.',
    specialization: ['blockchain', 'web_development', 'other'],
    yearsOfExperience: 6,
    totalStudentsTeaching: 324,
    totalCourses: 3,
    totalLiveClasses: 18,
    rating: {
      averageRating: 4.6,
      totalReviews: 98,
    },
    isEmailVerified: true,
    isPhoneVerified: true,
    isDocumentsVerified: false,
    isKYCVerified: true,
    isActive: false,
    isSuspended: true,
    createdAt: '2023-09-12T11:20:00Z',
    qualifications: [
      {
        degree: 'BS in Computer Science',
        institution: 'University of Texas',
        yearOfCompletion: 2018,
      },
    ],
    earnings: {
      totalEarnings: 32000,
      pendingPayment: 4000,
      paidAmount: 28000,
      currency: 'USD',
    },
    preferences: {
      emailNotifications: false,
      classReminders: false,
      studentUpdates: false,
      language: 'en',
      timezone: 'America/Chicago',
    },
  },
];
